#!/usr/bin/env -S uv run
from __future__ import annotations

import pprint

import wsjrdp2027


_LOGGER = __import__("logging").getLogger(__name__)

_EMAIL2KC = {
    "adrian.hoelzlwimmer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802028464,
        "disableableCredentialTypes": [],
        "email": "adrian.hoelzlwimmer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Adrian Nikolas",
        "id": "9bca8c20-2167-4ec8-992f-9b8c035ac263",
        "lastName": "Hölzlwimmer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "adrian.hoelzlwimmer@units.worldscoutjamboree.de",
    },
    "alex.weissoertel@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802066736,
        "disableableCredentialTypes": [],
        "email": "alex.weissoertel@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Alex Gabriel",
        "id": "4ffdeb3f-db3d-43d3-a448-a7af957d1881",
        "lastName": "Weissörtel",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "alex.weissoertel@units.worldscoutjamboree.de",
    },
    "alexander.klippe@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802065077,
        "disableableCredentialTypes": [],
        "email": "alexander.klippe@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Alexander",
        "id": "c58f7ab4-73b9-4632-a97a-e20566fd8386",
        "lastName": "Klippe",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "alexander.klippe@units.worldscoutjamboree.de",
    },
    "alexander.nickel@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802424632,
        "disableableCredentialTypes": [],
        "email": "alexander.nickel@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Alexander",
        "id": "bfa7d8cf-77af-4261-a9e2-052c0e4fddb0",
        "lastName": "Nickel",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "alexander.nickel@units.worldscoutjamboree.de",
    },
    "alysha.hoerl@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801988033,
        "disableableCredentialTypes": [],
        "email": "alysha.hoerl@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Alysha Maria",
        "id": "d1581e9a-9ccf-4461-860c-193ccf469e71",
        "lastName": "Hörl",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "alysha.hoerl@units.worldscoutjamboree.de",
    },
    "amelie.caspare@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801893912,
        "disableableCredentialTypes": [],
        "email": "amelie.caspare@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Amélie Marie Anita",
        "id": "f188afe8-7bf2-40c9-bee4-5721b0fe8ef0",
        "lastName": "Casparé",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "amelie.caspare@units.worldscoutjamboree.de",
    },
    "amelie.hartmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801628742,
        "disableableCredentialTypes": [],
        "email": "amelie.hartmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Amelie Alexandra",
        "id": "fe127328-e843-4838-8198-519db0c71c27",
        "lastName": "Hartmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "amelie.hartmann@units.worldscoutjamboree.de",
    },
    "antonia.pirkl@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802707774,
        "disableableCredentialTypes": [],
        "email": "antonia.pirkl@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Antonia",
        "id": "c419bd29-2c2e-46cd-b167-c9a0b820eea2",
        "lastName": "Pirkl",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "antonia.pirkl@units.worldscoutjamboree.de",
    },
    "antonia.strobl@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802216877,
        "disableableCredentialTypes": [],
        "email": "antonia.strobl@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Antonia Margarethe",
        "id": "4fbf5669-5fea-4b0c-a0ab-676957fd8b9b",
        "lastName": "Strobl",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "antonia.strobl@units.worldscoutjamboree.de",
    },
    "arne.gotzen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801775600,
        "disableableCredentialTypes": [],
        "email": "arne.gotzen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Arne",
        "id": "54436021-7cb7-4484-b459-9ef56a85b296",
        "lastName": "Gotzen",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "arne.gotzen@units.worldscoutjamboree.de",
    },
    "benedikt.cosler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801584424,
        "disableableCredentialTypes": [],
        "email": "benedikt.cosler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Benedikt",
        "id": "0d303c17-c785-4f4c-8905-3d6ff3271501",
        "lastName": "Cosler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "benedikt.cosler@units.worldscoutjamboree.de",
    },
    "bjarne.von-horn@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801837556,
        "disableableCredentialTypes": [],
        "email": "bjarne.von-horn@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Bjarne",
        "id": "7d830d0a-3b78-4b0e-9312-a7e81c897ed7",
        "lastName": "von Horn",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "bjarne.von-horn@units.worldscoutjamboree.de",
    },
    "bjoern.manthey@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802336712,
        "disableableCredentialTypes": [],
        "email": "bjoern.manthey@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Björn",
        "id": "bf5d479f-4dbe-4b27-a142-909f77307cc9",
        "lastName": "Manthey",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "bjoern.manthey@units.worldscoutjamboree.de",
    },
    "caspar.kotschate@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802794606,
        "disableableCredentialTypes": [],
        "email": "caspar.kotschate@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Caspar",
        "id": "d418b8c6-6f47-4e55-8a78-a3fe6741b0ab",
        "lastName": "Kotschate",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "caspar.kotschate@units.worldscoutjamboree.de",
    },
    "chiara.dimai@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802027548,
        "disableableCredentialTypes": [],
        "email": "chiara.dimai@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Chiara Isabella",
        "id": "c1ef67f0-9727-4364-8beb-6d2592f270e7",
        "lastName": "Dimai",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "chiara.dimai@units.worldscoutjamboree.de",
    },
    "christoph.von-oy@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801731297,
        "disableableCredentialTypes": [],
        "email": "christoph.von-oy@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Christoph",
        "id": "26f97f88-5d46-4705-89c7-bf1f837befa8",
        "lastName": "von Oy",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "christoph.von-oy@units.worldscoutjamboree.de",
    },
    "daniel.van-der-puetten@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801467190,
        "disableableCredentialTypes": [],
        "email": "daniel.van-der-puetten@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Daniel",
        "id": "1c4ee04e-6eb8-4e66-82bd-9dcc08f51da5",
        "lastName": "van der Pütten",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "daniel.van-der-puetten@units.worldscoutjamboree.de",
    },
    "daniel.weitsch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800858281,
        "disableableCredentialTypes": [],
        "email": "daniel.weitsch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Daniel",
        "id": "deeab719-2ead-4ab4-93ba-69293e5f6736",
        "lastName": "Weitsch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "daniel.weitsch@units.worldscoutjamboree.de",
    },
    "daniel.wimmer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801985499,
        "disableableCredentialTypes": [],
        "email": "daniel.wimmer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Daniel Alexander",
        "id": "b9a8f318-d098-4817-ac0c-dcf955f811cb",
        "lastName": "Wimmer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "daniel.wimmer@units.worldscoutjamboree.de",
    },
    "elena.el-gaziri@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802065901,
        "disableableCredentialTypes": [],
        "email": "elena.el-gaziri@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Elena Marie",
        "id": "04a9059e-d3cb-4dd3-9ea8-428010e105e1",
        "lastName": "El Gaziri",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "elena.el-gaziri@units.worldscoutjamboree.de",
    },
    "eliana.lenz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801374620,
        "disableableCredentialTypes": [],
        "email": "eliana.lenz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Eliana Wolfrune",
        "id": "d7f061cf-f103-44d9-8e2e-e42b37b59d0e",
        "lastName": "Lenz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "eliana.lenz@units.worldscoutjamboree.de",
    },
    "elias.pfaff@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801375491,
        "disableableCredentialTypes": [],
        "email": "elias.pfaff@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Elias Maxim",
        "id": "34d1c8f0-27cc-4dc1-bd8a-cc8677601f7e",
        "lastName": "Pfaff",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "elias.pfaff@units.worldscoutjamboree.de",
    },
    "emilia.kloeser@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802111956,
        "disableableCredentialTypes": [],
        "email": "emilia.kloeser@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Emilia Luise",
        "id": "61094b9c-e1a1-461b-afa0-3a5145e2d9b9",
        "lastName": "Klöser",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "emilia.kloeser@units.worldscoutjamboree.de",
    },
    "emilio.martin-sanchez-witte@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802335845,
        "disableableCredentialTypes": [],
        "email": "emilio.martin-sanchez-witte@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Emilio Luis Clemens",
        "id": "cd60dc98-3253-4252-b9d9-b60e867f3106",
        "lastName": "Martin Sanchez Witte",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "emilio.martin-sanchez-witte@units.worldscoutjamboree.de",
    },
    "emily.kissel@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800859992,
        "disableableCredentialTypes": [],
        "email": "emily.kissel@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Emily Louise",
        "id": "01de5324-a313-43ca-9d0f-67487d6319e9",
        "lastName": "Kissel",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "emily.kissel@units.worldscoutjamboree.de",
    },
    "erik.frielinghaus@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802287596,
        "disableableCredentialTypes": [],
        "email": "erik.frielinghaus@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Erik",
        "id": "080ee8d0-8d0b-401c-9618-d0b2e4be30c4",
        "lastName": "Frielinghaus",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "erik.frielinghaus@units.worldscoutjamboree.de",
    },
    "fabian.duffhauss@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801272337,
        "disableableCredentialTypes": [],
        "email": "fabian.duffhauss@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Fabian Andreas",
        "id": "5ba2a763-2b8e-4be1-a995-9103b5afafec",
        "lastName": "Duffhauß",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "fabian.duffhauss@units.worldscoutjamboree.de",
    },
    "fabian.luxenburger@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800859128,
        "disableableCredentialTypes": [],
        "email": "fabian.luxenburger@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Fabian Konstantin",
        "id": "902ab472-9dab-417f-835d-073e303f0b5e",
        "lastName": "Luxenburger",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "fabian.luxenburger@units.worldscoutjamboree.de",
    },
    "filippa.fischer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802627221,
        "disableableCredentialTypes": [],
        "email": "filippa.fischer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Filippa Sophie",
        "id": "019c5bd7-303b-4370-94af-6bb877a0ed04",
        "lastName": "Fischer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "filippa.fischer@units.worldscoutjamboree.de",
    },
    "florian.nolden@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801730400,
        "disableableCredentialTypes": [],
        "email": "florian.nolden@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Florian Denis",
        "id": "938b531c-df55-4b29-839b-cac7b06df73a",
        "lastName": "Nolden",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "florian.nolden@units.worldscoutjamboree.de",
    },
    "florian.schoen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802112815,
        "disableableCredentialTypes": [],
        "email": "florian.schoen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Florian Luca",
        "id": "a397e861-ded9-4b6b-9a06-f6aee3f33aff",
        "lastName": "Schön",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "florian.schoen@units.worldscoutjamboree.de",
    },
    "frederick.berger@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801937342,
        "disableableCredentialTypes": [],
        "email": "frederick.berger@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Frederick Maximilian",
        "id": "6044c6cb-41e8-49a1-9c34-be84e1fe409c",
        "lastName": "Berger",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "frederick.berger@units.worldscoutjamboree.de",
    },
    "fritz.steuernagel@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801024823,
        "disableableCredentialTypes": [],
        "email": "fritz.steuernagel@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Fritz",
        "id": "724c3dad-3983-4175-baf0-1c21a2b77bc4",
        "lastName": "Steuernagel",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "fritz.steuernagel@units.worldscoutjamboree.de",
    },
    "hanna.assmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802706882,
        "disableableCredentialTypes": [],
        "email": "hanna.assmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Hanna Yvonne",
        "id": "c055122a-af83-4ca6-ae2e-f674a88f7631",
        "lastName": "Aßmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "hanna.assmann@units.worldscoutjamboree.de",
    },
    "hannes.beckmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802749677,
        "disableableCredentialTypes": [],
        "email": "hannes.beckmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Hannes Torben",
        "id": "c4b5cfe1-fb24-4e4b-b939-e333c05910c7",
        "lastName": "Beckmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "hannes.beckmann@units.worldscoutjamboree.de",
    },
    "henry.allison@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801274922,
        "disableableCredentialTypes": [],
        "email": "henry.allison@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Henry William",
        "id": "fc7b01bb-042d-4ed0-b86e-7950c8862921",
        "lastName": "Allison",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "henry.allison@units.worldscoutjamboree.de",
    },
    "houdaifa.khalili@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801630402,
        "disableableCredentialTypes": [],
        "email": "houdaifa.khalili@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Houdaifa",
        "id": "d575d517-1d78-403b-a99e-0be3e034e91d",
        "lastName": "Khalili",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "houdaifa.khalili@units.worldscoutjamboree.de",
    },
    "ian.allgood@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802628036,
        "disableableCredentialTypes": [],
        "email": "ian.allgood@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Ian Paul",
        "id": "253cbb76-f5d4-4f54-b28c-cc8ac411f30b",
        "lastName": "Allgood",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ian.allgood@units.worldscoutjamboree.de",
    },
    "ida.stahlmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802705968,
        "disableableCredentialTypes": [],
        "email": "ida.stahlmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Ida Viktoria",
        "id": "dc15f860-f6ac-4821-9e75-cee9bf41ef7f",
        "lastName": "Stahlmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ida.stahlmann@units.worldscoutjamboree.de",
    },
    "isabella.kaiser@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802843525,
        "disableableCredentialTypes": [],
        "email": "isabella.kaiser@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Isabella",
        "id": "0a7ba09c-ad66-41c6-9407-4d146aa8daf1",
        "lastName": "Kaiser",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "isabella.kaiser@units.worldscoutjamboree.de",
    },
    "jakob.kaiser@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802842687,
        "disableableCredentialTypes": [],
        "email": "jakob.kaiser@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jakob",
        "id": "4493c610-bab4-45da-9ea2-654fc2b3e33c",
        "lastName": "Kaiser",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jakob.kaiser@units.worldscoutjamboree.de",
    },
    "jakob.plank@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801891368,
        "disableableCredentialTypes": [],
        "email": "jakob.plank@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jakob Sebastian",
        "id": "4fbc9f8b-ab66-4f29-8eef-353f89da6bcd",
        "lastName": "Plank",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jakob.plank@units.worldscoutjamboree.de",
    },
    "jan-malte.kroesche@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800971386,
        "disableableCredentialTypes": [],
        "email": "jan-malte.kroesche@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jan-Malte",
        "id": "d4268d2e-fb3a-4f8c-848f-9bf81b085e66",
        "lastName": "Krösche",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jan-malte.kroesche@units.worldscoutjamboree.de",
    },
    "jan.bast@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802422922,
        "disableableCredentialTypes": [],
        "email": "jan.bast@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jan",
        "id": "8def09e7-2b5d-490d-a3ba-a4e96833df56",
        "lastName": "Bast",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jan.bast@units.worldscoutjamboree.de",
    },
    "jan.koch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802381713,
        "disableableCredentialTypes": [],
        "email": "jan.koch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jan",
        "id": "3e5a9a4d-3200-4530-8308-66193ddccbd6",
        "lastName": "Koch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jan.koch@units.worldscoutjamboree.de",
    },
    "jan.mueller@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801418306,
        "disableableCredentialTypes": [],
        "email": "jan.mueller@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jan",
        "id": "7e3e4461-6012-445c-b605-414e1a5174bd",
        "lastName": "Müller",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jan.mueller@units.worldscoutjamboree.de",
    },
    "janina.greiert@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802425452,
        "disableableCredentialTypes": [],
        "email": "janina.greiert@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Janina Ann-Kathrin",
        "id": "b281888e-e217-4ce9-8c45-5befaea4de58",
        "lastName": "Greiert",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "janina.greiert@units.worldscoutjamboree.de",
    },
    "jasper.bensmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802384276,
        "disableableCredentialTypes": [],
        "email": "jasper.bensmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jasper",
        "id": "6796e9a0-3e1c-4eb1-afe3-81cb236c556c",
        "lastName": "Bensmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jasper.bensmann@units.worldscoutjamboree.de",
    },
    "jens.brune@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802423732,
        "disableableCredentialTypes": [],
        "email": "jens.brune@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jens",
        "id": "bd955002-1f6c-4c43-b152-853bbede2087",
        "lastName": "Brune",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jens.brune@units.worldscoutjamboree.de",
    },
    "jo.ries@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801197599,
        "disableableCredentialTypes": [],
        "email": "jo.ries@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jo",
        "id": "b8964213-d14c-4556-a4c5-a9255df502ef",
        "lastName": "Ries",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jo.ries@units.worldscoutjamboree.de",
    },
    "joachim.kahler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802288373,
        "disableableCredentialTypes": [],
        "email": "joachim.kahler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Joachim Maximilian",
        "id": "7e6fbcf8-57d4-43c9-b7c3-1050d322cab3",
        "lastName": "Kahler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "joachim.kahler@units.worldscoutjamboree.de",
    },
    "joerg.zender@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801776470,
        "disableableCredentialTypes": [],
        "email": "joerg.zender@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Joerg Philipp",
        "id": "73d6bf40-e9d2-467f-9ed3-c943d639766a",
        "lastName": "Zender",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "joerg.zender@units.worldscoutjamboree.de",
    },
    "johanna.viezens@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802382588,
        "disableableCredentialTypes": [],
        "email": "johanna.viezens@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Johanna Christina",
        "id": "473b911a-3f7a-487e-bc24-af89ab0f2b81",
        "lastName": "Viezens",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "johanna.viezens@units.worldscoutjamboree.de",
    },
    "johannes.horn@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802519035,
        "disableableCredentialTypes": [],
        "email": "johannes.horn@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Johannes Jakob",
        "id": "1fc2fa40-0bc8-489a-becb-799048d3d5fe",
        "lastName": "Horn",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "johannes.horn@units.worldscoutjamboree.de",
    },
    "jonas.heidegger@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801987149,
        "disableableCredentialTypes": [],
        "email": "jonas.heidegger@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jonas",
        "id": "2ba08597-5279-4ac9-aa8c-41671f4eed98",
        "lastName": "Heidegger",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jonas.heidegger@units.worldscoutjamboree.de",
    },
    "jonas.wagner@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802289193,
        "disableableCredentialTypes": [],
        "email": "jonas.wagner@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jonas",
        "id": "2827e0d3-13b5-4a84-9f0b-e323fd6b0be2",
        "lastName": "Wagner",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jonas.wagner@units.worldscoutjamboree.de",
    },
    "jonathan.hoelker@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801324465,
        "disableableCredentialTypes": [],
        "email": "jonathan.hoelker@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jonathan Tassilo",
        "id": "130b4b9f-d087-4ea2-96d7-9bc90a1b6752",
        "lastName": "Hölker",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jonathan.hoelker@units.worldscoutjamboree.de",
    },
    "jule.duckheim@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801468012,
        "disableableCredentialTypes": [],
        "email": "jule.duckheim@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jule",
        "id": "12f47028-fae4-4d1c-96ea-8aed70c2cfbd",
        "lastName": "Duckheim",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jule.duckheim@units.worldscoutjamboree.de",
    },
    "jule.reinhausen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801419131,
        "disableableCredentialTypes": [],
        "email": "jule.reinhausen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Jule",
        "id": "105536ba-e16e-4ce0-af19-e872c7e43316",
        "lastName": "Reinhausen",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "jule.reinhausen@units.worldscoutjamboree.de",
    },
    "julian.hohm@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802573156,
        "disableableCredentialTypes": [],
        "email": "julian.hohm@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Julian Steffen",
        "id": "6113ef86-53af-4215-8bf4-0d3c2a6647b7",
        "lastName": "Hohm",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "julian.hohm@units.worldscoutjamboree.de",
    },
    "julian.labouvie@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802067693,
        "disableableCredentialTypes": [],
        "email": "julian.labouvie@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Julian Luca",
        "id": "36666f85-e06c-4102-9574-770340b10508",
        "lastName": "Labouvie",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "julian.labouvie@units.worldscoutjamboree.de",
    },
    "juliano.kaplan@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802025714,
        "disableableCredentialTypes": [],
        "email": "juliano.kaplan@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Juliano Felix Emre",
        "id": "aa12a9f5-ea78-41bd-b5c8-d9c5bd4706c2",
        "lastName": "Kaplan",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "juliano.kaplan@units.worldscoutjamboree.de",
    },
    "justus.zilles@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802518196,
        "disableableCredentialTypes": [],
        "email": "justus.zilles@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Justus Alexander",
        "id": "565008d5-7e43-477e-b743-d87fb905f0ce",
        "lastName": "Zilles",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "justus.zilles@units.worldscoutjamboree.de",
    },
    "karoline.held@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802796307,
        "disableableCredentialTypes": [],
        "email": "karoline.held@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Karoline Elsa",
        "id": "f0200491-0d8b-44d9-b80f-25d490615e34",
        "lastName": "Held",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "karoline.held@units.worldscoutjamboree.de",
    },
    "katja.friske@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801465446,
        "disableableCredentialTypes": [],
        "email": "katja.friske@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Katja Renate",
        "id": "69bef12e-96bc-4a91-abd5-1b505d37ad2d",
        "lastName": "Friske",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "katja.friske@units.worldscoutjamboree.de",
    },
    "katja.winnerling@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802519906,
        "disableableCredentialTypes": [],
        "email": "katja.winnerling@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Katja",
        "id": "a8a225b3-4b3d-42b2-905f-c33d8b3cee12",
        "lastName": "Winnerling",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "katja.winnerling@units.worldscoutjamboree.de",
    },
    "kevin.thaler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801145584,
        "disableableCredentialTypes": [],
        "email": "kevin.thaler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Kevin",
        "id": "684bfe8d-ab40-4d06-b89e-348f374933b0",
        "lastName": "Thaler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "kevin.thaler@units.worldscoutjamboree.de",
    },
    "leandra.martens@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800970514,
        "disableableCredentialTypes": [],
        "email": "leandra.martens@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Leandra Antonia",
        "id": "609094e8-9655-41cc-9f3e-028b96c125a1",
        "lastName": "Martens",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "leandra.martens@units.worldscoutjamboree.de",
    },
    "lee.webb@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802157903,
        "disableableCredentialTypes": [],
        "email": "lee.webb@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lee Guinevere",
        "id": "063b5a43-a890-4ff3-b1bb-ddb296ec7135",
        "lastName": "Webb",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lee.webb@units.worldscoutjamboree.de",
    },
    "lena.fischer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802667330,
        "disableableCredentialTypes": [],
        "email": "lena.fischer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lena",
        "id": "735debc9-1af4-4fb6-bad9-07f0174b579b",
        "lastName": "Fischer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lena.fischer@units.worldscoutjamboree.de",
    },
    "lena.garske@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802517402,
        "disableableCredentialTypes": [],
        "email": "lena.garske@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lena Martina",
        "id": "cfde34fe-2fe1-42fd-8f5b-f636c37d791a",
        "lastName": "Garske",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lena.garske@units.worldscoutjamboree.de",
    },
    "leon.hrodek@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802026630,
        "disableableCredentialTypes": [],
        "email": "leon.hrodek@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Leon",
        "id": "4a9d1fe7-3fb6-4647-bd73-24899b91e728",
        "lastName": "Hrodek",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "leon.hrodek@units.worldscoutjamboree.de",
    },
    "leonie.leng@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801535707,
        "disableableCredentialTypes": [],
        "email": "leonie.leng@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Leonie",
        "id": "9c7c3b80-a1bc-427e-9ac7-17240e94b7ad",
        "lastName": "Leng",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "leonie.leng@units.worldscoutjamboree.de",
    },
    "leonie.ohagen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801732127,
        "disableableCredentialTypes": [],
        "email": "leonie.ohagen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Leonie Margareta",
        "id": "f19763b4-4973-4fd2-aafc-e399fd27e394",
        "lastName": "Ohagen",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "leonie.ohagen@units.worldscoutjamboree.de",
    },
    "leonie.sendker@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801732914,
        "disableableCredentialTypes": [],
        "email": "leonie.sendker@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Leonie Gesine",
        "id": "023363a3-5279-430f-9083-51173e27d60a",
        "lastName": "Sendker",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "leonie.sendker@units.worldscoutjamboree.de",
    },
    "lina.hoppe@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801534881,
        "disableableCredentialTypes": [],
        "email": "lina.hoppe@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lina",
        "id": "5a85e74a-f4ce-457b-81aa-24dd6629e6cf",
        "lastName": "Hoppe",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lina.hoppe@units.worldscoutjamboree.de",
    },
    "lina.schmid@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802216078,
        "disableableCredentialTypes": [],
        "email": "lina.schmid@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lina Teresa",
        "id": "a0062e45-08ae-4c6e-a9a4-e49ffbf27a95",
        "lastName": "Schmid",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lina.schmid@units.worldscoutjamboree.de",
    },
    "linus.hoehne@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802217670,
        "disableableCredentialTypes": [],
        "email": "linus.hoehne@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Linus Finn",
        "id": "14241e7c-e047-4ea0-912c-a1cab201e000",
        "lastName": "Höhne",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "linus.hoehne@units.worldscoutjamboree.de",
    },
    "louis.bauduin@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802705134,
        "disableableCredentialTypes": [],
        "email": "louis.bauduin@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Louis Jean",
        "id": "29276c4c-cf07-4b8b-aca9-6765ae9b6e99",
        "lastName": "Bauduin",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "louis.bauduin@units.worldscoutjamboree.de",
    },
    "luca.kisielewski@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802668172,
        "disableableCredentialTypes": [],
        "email": "luca.kisielewski@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Luca Michael",
        "id": "0a62bda3-7aca-45fa-8272-aa58aececfc5",
        "lastName": "Kisielewski",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "luca.kisielewski@units.worldscoutjamboree.de",
    },
    "ludwig.justl@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801986352,
        "disableableCredentialTypes": [],
        "email": "ludwig.justl@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Ludwig Sebastian",
        "id": "dd5c9237-9128-4708-8c1e-9d4eb56b0c69",
        "lastName": "Justl",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ludwig.justl@units.worldscoutjamboree.de",
    },
    "lukas.heissler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802628818,
        "disableableCredentialTypes": [],
        "email": "lukas.heissler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lukas",
        "id": "359cec1c-4fb3-4dd6-bc6c-81486921dab0",
        "lastName": "Heißler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lukas.heissler@units.worldscoutjamboree.de",
    },
    "lukas.kohlrautz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802383405,
        "disableableCredentialTypes": [],
        "email": "lukas.kohlrautz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lukas",
        "id": "6b7417d5-c0a8-4493-8b74-47c11b32ab66",
        "lastName": "Kohlrautz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lukas.kohlrautz@units.worldscoutjamboree.de",
    },
    "lukas.moser@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802114569,
        "disableableCredentialTypes": [],
        "email": "lukas.moser@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lukas Damian",
        "id": "0a3f3bf9-2dc7-48c0-bdaa-e9c3077d32c8",
        "lastName": "Moser",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lukas.moser@units.worldscoutjamboree.de",
    },
    "lukas.papperitz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801936445,
        "disableableCredentialTypes": [],
        "email": "lukas.papperitz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lukas Rafael",
        "id": "43fdb056-080e-4057-ad9f-fa1732171eea",
        "lastName": "Papperitz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lukas.papperitz@units.worldscoutjamboree.de",
    },
    "lukas.trumler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802752144,
        "disableableCredentialTypes": [],
        "email": "lukas.trumler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Lukas Valentin",
        "id": "c9aa6478-ecb1-45ec-9af1-8b0b95e7689e",
        "lastName": "Trumler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "lukas.trumler@units.worldscoutjamboree.de",
    },
    "madlen.raum@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801198471,
        "disableableCredentialTypes": [],
        "email": "madlen.raum@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Madlen",
        "id": "12fcbf4e-96a8-48c2-ae92-27c92681ef19",
        "lastName": "Raum",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "madlen.raum@units.worldscoutjamboree.de",
    },
    "maja.hofner@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802666499,
        "disableableCredentialTypes": [],
        "email": "maja.hofner@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Maja Katharina",
        "id": "d4b2113c-8e1c-4ea5-a45c-2a99b71269d1",
        "lastName": "Hofner",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "maja.hofner@units.worldscoutjamboree.de",
    },
    "maja.sonnenschein@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801838371,
        "disableableCredentialTypes": [],
        "email": "maja.sonnenschein@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Maja",
        "id": "1ccbe105-59df-4995-8419-5a65d74946b6",
        "lastName": "Sonnenschein",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "maja.sonnenschein@units.worldscoutjamboree.de",
    },
    "mareike.tielemans@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801733709,
        "disableableCredentialTypes": [],
        "email": "mareike.tielemans@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Mareike Ann Sophie",
        "id": "c4f022fb-0c38-4012-bded-005efec29ad2",
        "lastName": "Tielemans",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "mareike.tielemans@units.worldscoutjamboree.de",
    },
    "marina.frommherz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801892167,
        "disableableCredentialTypes": [],
        "email": "marina.frommherz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Marina Julia",
        "id": "6fe2a764-60f6-45d2-955e-dce284c31fc4",
        "lastName": "Frommherz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "marina.frommherz@units.worldscoutjamboree.de",
    },
    "marle.ruyter-hercules@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802750502,
        "disableableCredentialTypes": [],
        "email": "marle.ruyter-hercules@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Marle Johanna Therese",
        "id": "394e4a85-baec-4742-93ba-eaca2f659a40",
        "lastName": "Ruyter Hercules",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "marle.ruyter-hercules@units.worldscoutjamboree.de",
    },
    "marlene.sell@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801273183,
        "disableableCredentialTypes": [],
        "email": "marlene.sell@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Marlene Charlotte Allison",
        "id": "9156508f-8314-4c30-b120-6cff4b14a360",
        "lastName": "Sell",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "marlene.sell@units.worldscoutjamboree.de",
    },
    "mathis.rialland@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801372905,
        "disableableCredentialTypes": [],
        "email": "mathis.rialland@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Mathis Tim",
        "id": "057c52fe-24e6-416b-9e79-2913b0de6be6",
        "lastName": "Rialland",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "mathis.rialland@units.worldscoutjamboree.de",
    },
    "matthias.plechinger@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801836688,
        "disableableCredentialTypes": [],
        "email": "matthias.plechinger@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Matthias",
        "id": "4a96b66a-3d61-4449-9ea2-915beb8563c6",
        "lastName": "Plechinger",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "matthias.plechinger@units.worldscoutjamboree.de",
    },
    "maximilian.braun@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800972277,
        "disableableCredentialTypes": [],
        "email": "maximilian.braun@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Maximilian",
        "id": "78d9a3eb-407f-4eba-a974-0e57f1e4473f",
        "lastName": "Braun",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "maximilian.braun@units.worldscoutjamboree.de",
    },
    "maximilian.meinert@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801586133,
        "disableableCredentialTypes": [],
        "email": "maximilian.meinert@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Maximilian",
        "id": "14620fd3-7eb5-4e60-b235-aaafc5e55285",
        "lastName": "Meinert",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "maximilian.meinert@units.worldscoutjamboree.de",
    },
    "maya.rahmeier@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802626377,
        "disableableCredentialTypes": [],
        "email": "maya.rahmeier@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Maya Annika",
        "id": "fd8f0272-96d1-41e1-915c-21a5543a0d2c",
        "lastName": "Rahmeier",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "maya.rahmeier@units.worldscoutjamboree.de",
    },
    "melanie.moltke@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802797219,
        "disableableCredentialTypes": [],
        "email": "melanie.moltke@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Melanie",
        "id": "9f36a362-5003-4eef-9446-36778f4d17a2",
        "lastName": "Moltke",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "melanie.moltke@units.worldscoutjamboree.de",
    },
    "moritz.manal@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801839213,
        "disableableCredentialTypes": [],
        "email": "moritz.manal@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Moritz",
        "id": "47a4c7af-edbe-4035-812b-89b9be8f1e74",
        "lastName": "Manal",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "moritz.manal@units.worldscoutjamboree.de",
    },
    "moritz.pantel@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801681240,
        "disableableCredentialTypes": [],
        "email": "moritz.pantel@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Moritz",
        "id": "7be163d1-4151-4aa4-a5f4-9e79012c1ce5",
        "lastName": "Pantel",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "moritz.pantel@units.worldscoutjamboree.de",
    },
    "moritz.schwall@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801146380,
        "disableableCredentialTypes": [],
        "email": "moritz.schwall@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Moritz Tillmann Frithjof",
        "id": "59a93c09-c483-4992-92b4-325b0a33bdac",
        "lastName": "Schwall",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "moritz.schwall@units.worldscoutjamboree.de",
    },
    "nele.hahn@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801420855,
        "disableableCredentialTypes": [],
        "email": "nele.hahn@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nele",
        "id": "609e3d04-1f52-4f4b-a847-db9d6a0e7b45",
        "lastName": "Hahn",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nele.hahn@units.worldscoutjamboree.de",
    },
    "nele.hochkirchen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801585296,
        "disableableCredentialTypes": [],
        "email": "nele.hochkirchen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nele Marie",
        "id": "782272d6-0370-40e5-ac1d-7e055facd5c7",
        "lastName": "Hochkirchen",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nele.hochkirchen@units.worldscoutjamboree.de",
    },
    "nele.naplava@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801420036,
        "disableableCredentialTypes": [],
        "email": "nele.naplava@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nele Johanna",
        "id": "32610f57-7401-4cc2-a613-0089248b00f9",
        "lastName": "Naplava",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nele.naplava@units.worldscoutjamboree.de",
    },
    "nicklas.sternisa@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801196765,
        "disableableCredentialTypes": [],
        "email": "nicklas.sternisa@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nicklas",
        "id": "b9bc73fd-2ecd-4558-b0ed-1c51bcd07f15",
        "lastName": "Sternisa",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nicklas.sternisa@units.worldscoutjamboree.de",
    },
    "nicolas.lerch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802156940,
        "disableableCredentialTypes": [],
        "email": "nicolas.lerch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nicolas Alexander",
        "id": "81c28dbc-8be1-4cde-9c0f-e7dad05f54d8",
        "lastName": "Lerch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nicolas.lerch@units.worldscoutjamboree.de",
    },
    "niklas.moosburger@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801274058,
        "disableableCredentialTypes": [],
        "email": "niklas.moosburger@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Niklas",
        "id": "919f318c-17e6-4b94-adf7-6a1f4157d04a",
        "lastName": "Moosburger",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "niklas.moosburger@units.worldscoutjamboree.de",
    },
    "nikolas.jakobic@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801938163,
        "disableableCredentialTypes": [],
        "email": "nikolas.jakobic@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nikolas",
        "id": "cb33a9e5-72f1-4608-8356-67fe3ba95e1e",
        "lastName": "Jakobic",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nikolas.jakobic@units.worldscoutjamboree.de",
    },
    "nils.lang@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800973108,
        "disableableCredentialTypes": [],
        "email": "nils.lang@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nils",
        "id": "c434ddc8-d682-40a0-a329-db3b0de46f0a",
        "lastName": "Lang",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nils.lang@units.worldscoutjamboree.de",
    },
    "noah.eckstein@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801195917,
        "disableableCredentialTypes": [],
        "email": "noah.eckstein@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Noah",
        "id": "a5167014-2f70-461b-bd0a-e5f6ef35c16e",
        "lastName": "Eckstein",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "noah.eckstein@units.worldscoutjamboree.de",
    },
    "noah.thiemann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801583487,
        "disableableCredentialTypes": [],
        "email": "noah.thiemann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Noah Benjamin",
        "id": "c4135b01-eafc-403e-8a06-ca126aef744d",
        "lastName": "Thiemann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "noah.thiemann@units.worldscoutjamboree.de",
    },
    "nourddin.ajouaou@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801631232,
        "disableableCredentialTypes": [],
        "email": "nourddin.ajouaou@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Nourddin",
        "id": "c4bcb2f4-076e-4b2d-a6f8-0c50ff1365ed",
        "lastName": "Ajouaou",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "nourddin.ajouaou@units.worldscoutjamboree.de",
    },
    "patricia.rothweiler@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802751344,
        "disableableCredentialTypes": [],
        "email": "patricia.rothweiler@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Patricia",
        "id": "0a11c36e-3287-4ed5-a198-35d63c1f5725",
        "lastName": "Rothweiler",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "patricia.rothweiler@units.worldscoutjamboree.de",
    },
    "peggy.jankowski@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802334071,
        "disableableCredentialTypes": [],
        "email": "peggy.jankowski@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Peggy",
        "id": "bba6f014-167a-4b26-b3cc-da371ed1f0c5",
        "lastName": "Jankowski",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "peggy.jankowski@units.worldscoutjamboree.de",
    },
    "philip.soell@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801893013,
        "disableableCredentialTypes": [],
        "email": "philip.soell@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Philip",
        "id": "028c2dda-9fa0-4916-8df1-b42c060e31d2",
        "lastName": "Söll",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "philip.soell@units.worldscoutjamboree.de",
    },
    "philipp.burke@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801021479,
        "disableableCredentialTypes": [],
        "email": "philipp.burke@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Philipp",
        "id": "02fe1203-13c4-49ac-8a1d-e135d5e5780b",
        "lastName": "Burke",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "philipp.burke@units.worldscoutjamboree.de",
    },
    "philipp.oberdoerster@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801536536,
        "disableableCredentialTypes": [],
        "email": "philipp.oberdoerster@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Philipp",
        "id": "03b40dbd-8725-4e88-be76-ec7447f54bf1",
        "lastName": "Oberdörster",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "philipp.oberdoerster@units.worldscoutjamboree.de",
    },
    "queen.badom@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802158765,
        "disableableCredentialTypes": [],
        "email": "queen.badom@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Queen",
        "id": "b2a622f3-b5f7-4789-ba97-a6922092ccce",
        "lastName": "Badom",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "queen.badom@units.worldscoutjamboree.de",
    },
    "rebecca.papperitz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801935594,
        "disableableCredentialTypes": [],
        "email": "rebecca.papperitz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Rebecca Julia",
        "id": "449be6b6-eef0-477d-a667-935d5232bbe7",
        "lastName": "Papperitz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "rebecca.papperitz@units.worldscoutjamboree.de",
    },
    "ricarda.elsholz@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801147144,
        "disableableCredentialTypes": [],
        "email": "ricarda.elsholz@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Ricarda Josefine Petra",
        "id": "abec5985-e8ae-4616-b44b-aee62515d5e6",
        "lastName": "Elsholz",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ricarda.elsholz@units.worldscoutjamboree.de",
    },
    "rilana.rohde@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802290012,
        "disableableCredentialTypes": [],
        "email": "rilana.rohde@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Rilana",
        "id": "84eb3085-c5be-46c9-8a0f-0fac41569eb9",
        "lastName": "Rohde",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "rilana.rohde@units.worldscoutjamboree.de",
    },
    "roman.wanusch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802571428,
        "disableableCredentialTypes": [],
        "email": "roman.wanusch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Roman",
        "id": "830145b2-af54-48a5-aa64-3585ef676ae4",
        "lastName": "Wanusch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "roman.wanusch@units.worldscoutjamboree.de",
    },
    "ronny-werner.grohmann@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802334902,
        "disableableCredentialTypes": [],
        "email": "ronny-werner.grohmann@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Ronny-Werner",
        "id": "84eba4a5-f7f9-4374-a7bc-d6fb56f69a57",
        "lastName": "Grohmann",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ronny-werner.grohmann@units.worldscoutjamboree.de",
    },
    "safae.cherrati@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801629602,
        "disableableCredentialTypes": [],
        "email": "safae.cherrati@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Safae",
        "id": "4d714416-e8f0-4253-b668-5cc256de6712",
        "lastName": "Cherrati",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "safae.cherrati@units.worldscoutjamboree.de",
    },
    "samuel.draper@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767800857390,
        "disableableCredentialTypes": [],
        "email": "samuel.draper@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Samuel Adam",
        "id": "1b70a7f7-1bf0-4c58-9a11-d7d911358386",
        "lastName": "Draper",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "samuel.draper@units.worldscoutjamboree.de",
    },
    "sandra.boettrich@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801022306,
        "disableableCredentialTypes": [],
        "email": "sandra.boettrich@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Sandra Elisabeth",
        "id": "855980da-e0cd-4807-8101-f7f001c0565c",
        "lastName": "Böttrich",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "sandra.boettrich@units.worldscoutjamboree.de",
    },
    "selma.bruening@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801774745,
        "disableableCredentialTypes": [],
        "email": "selma.bruening@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Selma Theresa",
        "id": "f3cedaaf-ae0e-42ee-a850-d0b749cd684a",
        "lastName": "Brüning",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "selma.bruening@units.worldscoutjamboree.de",
    },
    "silas.barthold@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801373776,
        "disableableCredentialTypes": [],
        "email": "silas.barthold@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Silas",
        "id": "1189da64-008a-46d0-888f-5753ad85ccdb",
        "lastName": "Barthold",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "silas.barthold@units.worldscoutjamboree.de",
    },
    "simon.klein@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801537342,
        "disableableCredentialTypes": [],
        "email": "simon.klein@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Simon",
        "id": "5bbd45dc-869e-4ccb-b7a3-cdb5e0a8bbf8",
        "lastName": "Klein",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "simon.klein@units.worldscoutjamboree.de",
    },
    "simone.lapp@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801325331,
        "disableableCredentialTypes": [],
        "email": "simone.lapp@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Simone Debora",
        "id": "efb9522b-81de-4135-9415-c6a7d0cdfdb8",
        "lastName": "Lapp",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "simone.lapp@units.worldscoutjamboree.de",
    },
    "sophie.baggen@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801679557,
        "disableableCredentialTypes": [],
        "email": "sophie.baggen@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Sophie Elisabeth",
        "id": "a4b3dd85-444d-4029-a591-1d274c41f0ea",
        "lastName": "Baggen",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "sophie.baggen@units.worldscoutjamboree.de",
    },
    "stefan.deobald@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801023986,
        "disableableCredentialTypes": [],
        "email": "stefan.deobald@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Stefan Gerhard",
        "id": "f542f5a3-b4a6-4064-89f9-4c36b4da99b1",
        "lastName": "Deobald",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "stefan.deobald@units.worldscoutjamboree.de",
    },
    "steffen.ludwig@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801326280,
        "disableableCredentialTypes": [],
        "email": "steffen.ludwig@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Steffen",
        "id": "4c08c44e-051a-4e87-b1fc-293a9e8c1cec",
        "lastName": "Ludwig",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "steffen.ludwig@units.worldscoutjamboree.de",
    },
    "stephan.schockert@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801682077,
        "disableableCredentialTypes": [],
        "email": "stephan.schockert@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Stephan Wilhelm",
        "id": "a1c61932-57b7-4ee2-9800-05571b3294b7",
        "lastName": "Schockert",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "stephan.schockert@units.worldscoutjamboree.de",
    },
    "stephanie.lokotsch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801466347,
        "disableableCredentialTypes": [],
        "email": "stephanie.lokotsch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Stephanie",
        "id": "10cf5bf4-e60c-4233-be50-a57a15575694",
        "lastName": "Lokotsch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "stephanie.lokotsch@units.worldscoutjamboree.de",
    },
    "sven.pollak@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802665668,
        "disableableCredentialTypes": [],
        "email": "sven.pollak@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Sven Udo",
        "id": "c0e47812-ef51-4523-ab97-694fb7244d19",
        "lastName": "Pollak",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "sven.pollak@units.worldscoutjamboree.de",
    },
    "tamara.lapper@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801144757,
        "disableableCredentialTypes": [],
        "email": "tamara.lapper@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Tamara Luise",
        "id": "f04ef0b4-e2fa-407e-991b-de67b32aa23c",
        "lastName": "Lapper",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "tamara.lapper@units.worldscoutjamboree.de",
    },
    "theo.samadi@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801323666,
        "disableableCredentialTypes": [],
        "email": "theo.samadi@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Theo Kian",
        "id": "2a961e7a-7fa9-4751-957f-991fcf8646c8",
        "lastName": "Samadi",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "theo.samadi@units.worldscoutjamboree.de",
    },
    "thomas.westphal@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801680429,
        "disableableCredentialTypes": [],
        "email": "thomas.westphal@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Thomas",
        "id": "75d28457-8489-4067-abee-f5c89691d8f6",
        "lastName": "Westphal",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "thomas.westphal@units.worldscoutjamboree.de",
    },
    "tiemo.tom-dieck@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802218607,
        "disableableCredentialTypes": [],
        "email": "tiemo.tom-dieck@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Tiemo",
        "id": "20f329d1-c687-49e1-9dc8-cc5435a7e88e",
        "lastName": "tom Dieck",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "tiemo.tom-dieck@units.worldscoutjamboree.de",
    },
    "till.luetkenhaus@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801777303,
        "disableableCredentialTypes": [],
        "email": "till.luetkenhaus@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Till",
        "id": "c610c11f-524e-4def-a7a0-91874fee8173",
        "lastName": "Lütkenhaus",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "till.luetkenhaus@units.worldscoutjamboree.de",
    },
    "tim.breuer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802795505,
        "disableableCredentialTypes": [],
        "email": "tim.breuer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Tim Lukas",
        "id": "fc78e6d6-bb74-413d-b34d-997baee3bd46",
        "lastName": "Breuer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "tim.breuer@units.worldscoutjamboree.de",
    },
    "timo.busch@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802844328,
        "disableableCredentialTypes": [],
        "email": "timo.busch@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Timo",
        "id": "cf3c2a1a-8e7d-467f-b34a-2bfe9340ad70",
        "lastName": "Busch",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "timo.busch@units.worldscoutjamboree.de",
    },
    "tobias.hofauer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802155987,
        "disableableCredentialTypes": [],
        "email": "tobias.hofauer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Tobias Simon",
        "id": "11554d6e-7db0-4925-8da2-1a176153d87e",
        "lastName": "Hofauer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "tobias.hofauer@units.worldscoutjamboree.de",
    },
    "tobias.scheurich@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802572284,
        "disableableCredentialTypes": [],
        "email": "tobias.scheurich@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Tobias",
        "id": "e6e684bd-a516-4eb5-a4fe-6f47626813e9",
        "lastName": "Scheurich",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "tobias.scheurich@units.worldscoutjamboree.de",
    },
    "ulrich.iksinski@units.worldscoutjamboree.de": {
        "attributes": {"mossEmail": ["wsj27-484@worldscoutjamboree.de"]},
        "createdTimestamp": 1769614956482,
        "disableableCredentialTypes": [],
        "email": "ulrich.iksinski@units.worldscoutjamboree.de",
        "emailVerified": True,
        "enabled": True,
        "firstName": "Ulrich",
        "id": "ee983b1f-4fb2-4c4b-befa-ec2994b68f36",
        "lastName": "Iksinski",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "ulrich.iksinski@units.worldscoutjamboree.de",
    },
    "veronika.loeser@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767801023159,
        "disableableCredentialTypes": [],
        "email": "veronika.loeser@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Veronika Carmen",
        "id": "e166cb8b-bf31-4958-a069-9eb80e45edc5",
        "lastName": "Löser",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "veronika.loeser@units.worldscoutjamboree.de",
    },
    "viktoria.harbauer@units.worldscoutjamboree.de": {
        "createdTimestamp": 1767802113666,
        "disableableCredentialTypes": [],
        "email": "viktoria.harbauer@units.worldscoutjamboree.de",
        "emailVerified": False,
        "enabled": True,
        "firstName": "Viktoria Sophie",
        "id": "bfa2b646-c82b-4cee-8530-0811dadd745f",
        "lastName": "Harbauer",
        "notBefore": 0,
        "requiredActions": [],
        "totp": False,
        "username": "viktoria.harbauer@units.worldscoutjamboree.de",
    },
}
_USERNAME2KC = {user["username"]: user for user in _EMAIL2KC.values()}


_EXT_EHOC_USERNAMES = [
    "ihoefig",
    "cwindisch",
    "funger",
    "pneubauer",
    "dfritzsche",
    "cespeter",
    "eguldenfels",
    "kwistal",
    "mgriwatz",
    "klangenberg",
    "lriesner",
    "vreichenspurner",
    "hrieger",
]


def main():
    ctx = wsjrdp2027.WsjRdpContext(
        parse_arguments=False,
        __file__=__file__,
        # dry_run=True,
    )
    out_base = ctx.make_out_path("sync_cmt_keycloak__{{ filename_suffix }}")
    log_filename = out_base.with_suffix(".log")
    ctx.configure_log_file(log_filename)

    email2keycloak_user = {}
    username2keycloak_user = {}

    # for group_name in ["CMT"]:
    # for group_name in ["CMT", "BMT", "IST", "UL"]:
    for group_name in ["UL"]:
        keycloak_users_cmt = wsjrdp2027.keycloak.get_users_in_group(ctx, group_name)
        keycloak_users_cmt = [user for user in keycloak_users_cmt if user["enabled"]]

        # for i, user in enumerate(keycloak_users_cmt):
        #     print()
        #     username = user['username']
        #     print(i, username)
        #     user_old = _USERNAME2KC[user['username']]
        #     ctx.keycloak.update_user(username, user_old)#, dry_run=True)
        #
        # raise SystemExit(42)

        missing_emails = []
        for user in keycloak_users_cmt:
            if "email" not in user:
                print()
                print("Missing email!")
                print(user)
                missing_emails.append(user["username"])

        print(len(missing_emails), "with missing email")

        email2keycloak_user.update(
            {user["email"]: user for user in keycloak_users_cmt if user["enabled"]}
        )
        username2keycloak_user.update(
            {user["username"]: user for user in keycloak_users_cmt if user["enabled"]}
        )
        _LOGGER.info(
            f"Found {len(keycloak_users_cmt)} enabled {group_name} users in Keycloak"
        )
    _LOGGER.debug(f"email2keycloak_user = {pprint.pformat(email2keycloak_user)}")

    errors = []

    email2row = {}

    wsjrdp_email_values = []
    moss_email_values = []

    ctx.require_approval_to_run_in_prod()

    with ctx.psycopg_connect() as conn:
        df = wsjrdp2027.load_people_dataframe(
            conn,
            where=wsjrdp2027.PeopleWhere(
                role="UL", exclude_deregistered=True, exclude_primary_group_id=[5, 6, 7]
            ),
            # where=wsjrdp2027.PeopleWhere(primary_group_id=1, exclude_deregistered=True),
            # where=wsjrdp2027.PeopleWhere(id=[21, 65, 413], exclude_deregistered=True),
            log_resulting_data_frame=False,
        )
        _LOGGER.info(f"Found {len(df)} not-deregistered contingent members in Hitobito")

        for p in wsjrdp2027.iter_people_dataframe(df):
            email2row[p.wsjrdp_email] = p

            if not (keycloak_user := email2keycloak_user.get(p.wsjrdp_email)):
                if p["id"] == 1871:
                    _LOGGER.debug(
                        f"{p.role_id_name}: Ignore missing keycloak user (Till Sanders)"
                    )
                else:
                    errors.append(f"{p.role_id_name}: Could not find Keycloak user")
                continue
            keycloak_moss_email = keycloak_user.get("attributes", {}).get(
                "mossEmail", [None]
            )[0]
            if p.moss_email is None:
                errors.append(f"{p.role_id_name}: Missing moss_email")
                continue
            elif keycloak_moss_email is None:
                _LOGGER.info(
                    f"{p.role_id_name}: Missing mossEmail, will set to {p.moss_email}"
                )
                ctx.keycloak.update_user(
                    keycloak_user["username"],
                    {"attributes": {"mossEmail": [p.moss_email]}},
                )
            elif keycloak_moss_email != p.moss_email:
                if keycloak_moss_email.lower() == p.moss_email:
                    _LOGGER.info(
                        f"{p.role_id_name}: Fix mossEmail {keycloak_moss_email!r} -> {p.moss_email!r}"
                    )
                    ctx.keycloak.update_user(
                        keycloak_user["username"],
                        {"attributes": {"mossEmail": [p.moss_email]}},
                    )
                else:
                    errors.append(
                        f"{p.role_id_name}: Unexpected mossEmail={keycloak_moss_email!r}"
                    )
                    continue
            if "wsjrdp_email" not in p.additional_info or p["id"]:
                wsjrdp_email_values.append(
                    {"id": p["id"], "wsjrdp_email": p.wsjrdp_email}
                )
            if "moss_email" not in p.additional_info or p["id"]:
                moss_email_values.append({"id": p["id"], "moss_email": p.moss_email})

        if errors:
            for err in errors:
                _LOGGER.error(err)
            return 1
        return 23

        # if wsjrdp_email_values:
        #     _LOGGER.info(f"Update wsjrdp_email for {len(wsjrdp_email_values)} people")
        #     wsjrdp2027.pg.pg_update_people_additional_info_email(
        #         conn, "wsjrdp_email", wsjrdp_email_values, now=ctx.start_time
        #     )
        # else:
        #     _LOGGER.info("No need to update wsjrdp_email for synced people")
        #
        # if moss_email_values:
        #     _LOGGER.info(f"Update moss_email for {len(moss_email_values)} people")
        #     wsjrdp2027.pg.pg_update_people_additional_info_email(
        #         conn, "moss_email", moss_email_values, now=ctx.start_time
        #     )
        # else:
        #     _LOGGER.info("No need to update moss_email for synced people")

    # Update keycloak users

    for email, user in email2keycloak_user.items():
        keycloak_moss_email = user.get("attributes", {}).get("mossEmail", [None])[0]
        assert email == user["email"]
        if email not in email2row:
            if user["username"] in ("umanagement", "bpowell"):
                _LOGGER.info(
                    f"{email}: Ignore, not expected to have associated Hitobito account"
                )
            elif user["username"] in ["aothmer", "lriesner", "mdenzer", "vvorholz"]:
                if keycloak_moss_email == email:
                    _LOGGER.info(
                        f"{email}: No Hitobito account yet, mossEmail == email == {email}"
                    )
                elif keycloak_moss_email is None:
                    _LOGGER.info(
                        f"{email}: No Hitobito account yet, set mossEmail to {email}"
                    )
                    wsjrdp2027.keycloak.update_user(
                        ctx,
                        user["username"],
                        {"attributes": {"mossEmail": [user["email"]]}},
                    )
                else:
                    errors.append(
                        f"Unexpected mossEmail == {keycloak_moss_email!r} where email = {email!r}"
                    )
            else:
                errors.append(
                    f"No Hitobito user for Keycloak user {user['username']}, email={user['email']}"
                )

    if errors:
        for err in errors:
            _LOGGER.error(err)
        return 1

    _LOGGER.info("")
    _LOGGER.info(
        f"Moss E-Mail Adresses for eHOC+ ({len(_EXT_EHOC_USERNAMES)} members in list)"
    )
    for username in _EXT_EHOC_USERNAMES:
        user = username2keycloak_user[username]
        print(user["email"])
    print()

    _LOGGER.info("")
    _LOGGER.info("Output directory: %s", ctx.out_dir)
    _LOGGER.info("  Log file: %s", log_filename)


if __name__ == "__main__":
    __import__("sys").exit(main())
