[pytest]
addopts =
    --doctest-modules
    --doctest-continue-on-failure
    --pyargs
    --showlocals
    -vv
    -p pytest_wsjrdp2027
    # --capture=no

norecursedirs =
    build
    dist
    2023
    integration-tests

log_level = DEBUG

# log_cli = true
# log_cli_level = DEBUG
