from __future__ import annotations

import typing as _typing


if _typing.TYPE_CHECKING:
    import collections.abc as _collections_abc


_DATEV_EXTF_BUCHUNGSSTAPEL_COLUMNS = [
    "Umsatz (ohne Soll/Haben-Kz)",
    "Soll/Haben-Kennzeichen",
    "WKZ Umsatz",
    "Kurs",
    "Basis-Umsatz",
    "WKZ Basis-Umsatz",
    "Konto",
    "Gegenkonto (ohne BU-Schlüssel)",
    "BU-Schlüssel",
    "Belegdatum",
    "Belegfeld 1",
    "Belegfeld 2",
    "Skonto",
    "Buchungstext",
    "Postensperre",
    "Diverse Adressnummer",
    "Geschäftspartnerbank",
    "Sachverhalt",
    "Zinssperre",
    "Beleglink",
    "Beleginfo - Art 1",
    "Beleginfo - Inhalt 1",
    "Beleginfo - Art 2",
    "Beleginfo - Inhalt 2",
    "Beleginfo - Art 3",
    "Beleginfo - Inhalt 3",
    "Beleginfo - Art 4",
    "Beleginfo - Inhalt 4",
    "Beleginfo - Art 5",
    "Beleginfo - Inhalt 5",
    "Beleginfo - Art 6",
    "Beleginfo - Inhalt 6",
    "Beleginfo - Art 7",
    "Beleginfo - Inhalt 7",
    "Beleginfo - Art 8",
    "Beleginfo - Inhalt 8",
    "KOST1 - Kostenstelle",
    "KOST2 - Kostenstelle",
    "Kost-Menge",
    "EU-Land u. UStID (Bestimmung)",
    "EU-Steuersatz (Bestimmung)",
    "Abw. Versteuerungsart",
    "Sachverhalt L+L",
    "Funktionsergänzung L+L",
    "BU 49 Hauptfunktionstyp",
    "BU 49 Hauptfunktionsnummer",
    "BU 49 Funktionsergänzung",
    "Zusatzinformation - Art 1",
    "Zusatzinformation- Inhalt 1",
    "Zusatzinformation - Art 2",
    "Zusatzinformation- Inhalt 2",
    "Zusatzinformation - Art 3",
    "Zusatzinformation- Inhalt 3",
    "Zusatzinformation - Art 4",
    "Zusatzinformation- Inhalt 4",
    "Zusatzinformation - Art 5",
    "Zusatzinformation- Inhalt 5",
    "Zusatzinformation - Art 6",
    "Zusatzinformation- Inhalt 6",
    "Zusatzinformation - Art 7",
    "Zusatzinformation- Inhalt 7",
    "Zusatzinformation - Art 8",
    "Zusatzinformation- Inhalt 8",
    "Zusatzinformation - Art 9",
    "Zusatzinformation- Inhalt 9",
    "Zusatzinformation - Art 10",
    "Zusatzinformation- Inhalt 10",
    "Zusatzinformation - Art 11",
    "Zusatzinformation- Inhalt 11",
    "Zusatzinformation - Art 12",
    "Zusatzinformation- Inhalt 12",
    "Zusatzinformation - Art 13",
    "Zusatzinformation- Inhalt 13",
    "Zusatzinformation - Art 14",
    "Zusatzinformation- Inhalt 14",
    "Zusatzinformation - Art 15",
    "Zusatzinformation- Inhalt 15",
    "Zusatzinformation - Art 16",
    "Zusatzinformation- Inhalt 16",
    "Zusatzinformation - Art 17",
    "Zusatzinformation- Inhalt 17",
    "Zusatzinformation - Art 18",
    "Zusatzinformation- Inhalt 18",
    "Zusatzinformation - Art 19",
    "Zusatzinformation- Inhalt 19",
    "Zusatzinformation - Art 20",
    "Zusatzinformation- Inhalt 20",
    "Stück",
    "Gewicht",
    "Zahlweise",
    "Forderungsart",
    "Veranlagungsjahr",
    "Zugeordnete Fälligkeit",
    "Skontotyp",
    "Auftragsnummer",
    "Buchungstyp",
    "USt-Schlüssel (Anzahlungen)",
    "EU-Land (Anzahlungen)",
    "Sachverhalt L+L (Anzahlungen)",
    "EU-Steuersatz (Anzahlungen)",
    "Erlöskonto (Anzahlungen)",
    "Herkunft-Kz",
    "Buchungs GUID",
    "KOST-Datum",
    "SEPA-Mandatsreferenz",
    "Skontosperre",
    "Gesellschaftername",
    "Beteiligtennummer",
    "Identifikationsnummer",
    "Zeichnernummer",
    "Postensperre bis",
    "Bezeichnung SoBil-Sachverhalt",
    "Kennzeichen SoBil-Buchung",
    "Festschreibung",
    "Leistungsdatum",
    "Datum Zuord. Steuerperiode",
    "Fälligkeit",
    "Generalumkehr (GU)",
    "Steuersatz",
    "Land",
    "Abrechnungsreferenz",
    "BVV-Position",
    "EU-Land u. UStID (Ursprung)",
    "EU-Steuersatz (Ursprung)",
    "Abw. Skontokonto",
]


_EXTF_TYPES = {
    "Umsatz (ohne Soll/Haben-Kz)": "Betrag",
    "Soll/Haben-Kennzeichen": "Text",
    "WKZ Umsatz": "Text",
    "Kurs": "Zahl",
    "Basis-Umsatz": "Betrag",
    "WKZ Basis-Umsatz": "Text",
    "Kontonummer": "Konto",
    "Konto": "Konto",
    "Gegenkonto (ohne BU-Schlüssel)": "Konto",
    "BU-Schlüssel": "Text",
    "Belegdatum": "Datum",
    "Belegfeld 1": "Text",
    "Belegfeld 2": "Text",
    "Skonto": "Betrag",
    "Buchungstext": "Text",
    "Postensperre": "Zahl",
    "Diverse Adressnummer": "Text",
    "Geschäftspartnerbank": "Zahl",
    "Sachverhalt": "Zahl",
    "Zinssperre": "Zahl",
    "Beleglink": "Text",
    "Beleginfo - Art 1": "Text",
    "Beleginfo - Inhalt 1": "Text",
    "Beleginfo - Art 2": "Text",
    "Beleginfo - Inhalt 2": "Text",
    "Beleginfo - Art 3": "Text",
    "Beleginfo - Inhalt 3": "Text",
    "Beleginfo - Art 4": "Text",
    "Beleginfo - Inhalt 4": "Text",
    "Beleginfo - Art 5": "Text",
    "Beleginfo - Inhalt 5": "Text",
    "Beleginfo - Art 6": "Text",
    "Beleginfo - Inhalt 6": "Text",
    "Beleginfo - Art 7": "Text",
    "Beleginfo - Inhalt 7": "Text",
    "Beleginfo - Art 8": "Text",
    "Beleginfo - Inhalt 8": "Text",
    "Kost 1 - Kostenstelle": "Text",
    "Kost 2 - Kostenstelle": "Text",
    "KOST1 - Kostenstelle": "Text",
    "KOST2 - Kostenstelle": "Text",
    "Kost-Menge": "Zahl",
    "EU-Land u. UStID (Bestimmung)": "Text",
    "EU-Steuersatz (Bestimmung)": "Zahl",
    "Abw. Versteuerungsart": "Text",
    "Sachverhalt L+L": "Zahl",
    "Funktionsergänzung L+L": "Zahl",
    "BU 49 Hauptfunktionstyp": "Zahl",
    "BU 49 Hauptfunktionsnummer": "Zahl",
    "BU 49 Funktionsergänzung": "Zahl",
    "Zusatzinformation - Art 1": "Text",
    "Zusatzinformation- Inhalt 1": "Text",
    "Zusatzinformation - Art 2": "Text",
    "Zusatzinformation- Inhalt 2": "Text",
    "Zusatzinformation - Art 3": "Text",
    "Zusatzinformation- Inhalt 3": "Text",
    "Zusatzinformation - Art 4": "Text",
    "Zusatzinformation- Inhalt 4": "Text",
    "Zusatzinformation - Art 5": "Text",
    "Zusatzinformation- Inhalt 5": "Text",
    "Zusatzinformation - Art 6": "Text",
    "Zusatzinformation- Inhalt 6": "Text",
    "Zusatzinformation - Art 7": "Text",
    "Zusatzinformation- Inhalt 7": "Text",
    "Zusatzinformation - Art 8": "Text",
    "Zusatzinformation- Inhalt 8": "Text",
    "Zusatzinformation - Art 9": "Text",
    "Zusatzinformation- Inhalt 9": "Text",
    "Zusatzinformation - Art 10": "Text",
    "Zusatzinformation- Inhalt 10": "Text",
    "Zusatzinformation - Art 11": "Text",
    "Zusatzinformation- Inhalt 11": "Text",
    "Zusatzinformation - Art 12": "Text",
    "Zusatzinformation- Inhalt 12": "Text",
    "Zusatzinformation - Art 13": "Text",
    "Zusatzinformation- Inhalt 13": "Text",
    "Zusatzinformation - Art 14": "Text",
    "Zusatzinformation- Inhalt 14": "Text",
    "Zusatzinformation - Art 15": "Text",
    "Zusatzinformation- Inhalt 15": "Text",
    "Zusatzinformation - Art 16": "Text",
    "Zusatzinformation- Inhalt 16": "Text",
    "Zusatzinformation - Art 17": "Text",
    "Zusatzinformation- Inhalt 17": "Text",
    "Zusatzinformation - Art 18": "Text",
    "Zusatzinformation- Inhalt 18": "Text",
    "Zusatzinformation - Art 19": "Text",
    "Zusatzinformation- Inhalt 19": "Text",
    "Zusatzinformation - Art 20": "Text",
    "Zusatzinformation- Inhalt 20": "Text",
    "Stück": "Zahl",
    "Gewicht": "Zahl",
    "Zahlweise": "Zahl",
    "Forderungsart": "Text",
    "Veranlagungsjahr": "Zahl",
    "Zugeordnete Fälligkeit": "Datum",
    "Skontotyp": "Zahl",
    "Auftragsnummer": "Text",
    "Buchungstyp (Anzahlungen)": "Text",
    "Buchungstyp": "Text",
    "USt-Schlüssel (Anzahlungen)": "Zahl",
    "EU-Land (Anzahlungen)": "Text",
    "Sachverhalt L+L (Anzahlungen)": "Zahl",
    "EU-Steuersatz (Anzahlungen)": "Zahl",
    "Erlöskonto (Anzahlungen)": "Konto",
    "Herkunft-Kz": "Text",
    "Buchungs GUID": "Text",
    "Kost-Datum": "Datum",
    "KOST-Datum": "Datum",
    "SEPA-Mandatsreferenz": "Text",
    "Skontosperre": "Zahl",
    "Gesellschaftername": "Text",
    "Beteiligtennummer": "Zahl",
    "Identifikationsnummer": "Text",
    "Zeichnernummer": "Text",
    "Postensperre bis": "Datum",
    "Bezeichnung SoBil-Sachverhalt": "Text",
    "Kennzeichen SoBil-Buchung": "Zahl",
    "Festschreibung": "Zahl",
    "Leistungsdatum": "Datum",
    "Datum Zuord. Steuerperiode": "Datum",
    "Fälligkeit": "Datum",
    "Generalumkehr (GU)": "Text",
    "Steuersatz": "Zahl",
    "Land": "Text",
    "Abrechnungsreferenz": "Text",
    "BVV-Position": "Zahl",
    "EU-Land u. UStID (Ursprung)": "Text",
    "EU-Steuersatz (Ursprung)": "Zahl",
    "Abw. Skontokonto": "Konto",
}


class DatevExtfWriter:
    def __init__(
        self, file, *, fieldnames: _collections_abc.Iterable[str] | None = None
    ) -> None:
        if fieldnames is None:
            fieldnames = _DATEV_EXTF_BUCHUNGSSTAPEL_COLUMNS
        else:
            fieldnames = list(fieldnames)

        self._file = file
        self._fieldnames = fieldnames
        unsupported_fields = []
        for spalte in self._fieldnames:
            if spalte not in _EXTF_TYPES:
                unsupported_fields.append(spalte)
        if unsupported_fields:
            raise RuntimeError(
                f"Unsupported fields: {'\n    '.join(str(f) for f in unsupported_fields)}"
            )

    def _serialize_field(self, field_name: str, value) -> str:
        field_type = _EXTF_TYPES[field_name]
        if value is None:
            value = ""
        if field_type == "Text":
            value = '"' + str(value).replace('"', '""') + '"'
        else:
            value = str(value)
            assert '"' not in value
        return value

    def writeheader(self) -> None:
        self._file.write(";".join(field_name for field_name in self._fieldnames))
        self._file.write("\n")

    def writerow(self, rowdict, /) -> None:
        d = {field_name: "" for field_name in self._fieldnames}
        d.update(rowdict)
        line = ";".join(
            self._serialize_field(field_name, rowdict.get(field_name, ""))
            for field_name in self._fieldnames
        )
        self._file.write(line)
        self._file.write("\n")
