#!/usr/bin/env -S uv run
"""Import Moss **card transactions** (WSJ27 Custom-CSV) into two tables.

Source: the Moss CSV-Builder "WSJ27" export of the *Transaction* format (see
hitobito_wsjrdp_2027/doc/moss_data_model.md section 5.2). Semicolon-separated,
UTF-8, ISO dates (YYYY-MM-DD), decimal point ".".

Target (one CSV row = one split of a card transaction):
  * moss_card_transactions          -- one row per `Transaction ID`
    (= card_transaction_uuid); fields identical across splits.
  * moss_card_transaction_bookings  -- one row per split; fields that differ per
    split. References its transaction by the natural key `card_transaction_uuid`.

Column handling (see doc 5.2.7):
  * OTHER_COLUMNS_*  -- >70%-empty columns -> the target's `other_moss_columns` jsonb,
                        only when a value is present.
  * DERIVED_FROM_UUID -- Moss Record/Attachment URL + Transaction ID PDF filename:
                        NOT stored (derivable from the Transaction ID); stashed
                        into the transaction's other_moss_columns only if the CSV value
                        deviates from the derived one.
  * ALWAYS_MIRROR_* -- every amount/currency/rate column, mirrored verbatim into
                        `other_moss_columns` under its Moss name, even when a
                        house column holds the same value (source fidelity).
  * IGNORED / NOT_EXPORTED -- present in the CSV but never stored.

Money columns follow doc/money_conventions.md: Moss delivers SIGNED amounts, so
`signed_base_amount` (Home) / `signed_transaction_amount` (Original) are stored
as-is and the unsigned `base_amount` / `transaction_amount` plus `debit_credit`
are generated by the DB. `exchange_rate` and the Kontenart columns
(`account_kind` on the lines, `supplier_account_kind` /
`moss_balance_account_kind` / `cash_in_transit_account_kind` on the transaction)
are derived here; the matching `*_type` classes are generated by the DB.
`signed_total_base_amount` is the sum of a transaction's lines, cross-checked
against the Moss "Total Amount". Non-EUR Home Currency is refused.

`source_file` is provenance, not content: it is kept out of the diffed column
sets, so a renamed file alone never triggers an UPDATE -- it is written on INSERT
and refreshed only on rows that change anyway (same rule as the DTVF importer).

Manual / Hitobito-side columns (subject_id/subject_type, comment, status,
additional_info; the
DATEV links moss_card_transactions.clearing_datev_booking_id and the booking's
expense_datev_booking_id, each with their *_link_meta) are NEVER written and are
preserved on UPDATE (only Moss-mapped columns + other_moss_columns are refreshed).

Import logic, keyed on `Transaction ID` (= card_transaction_uuid):
  1. No DB transaction     -> INSERT the transaction + all its booking rows.
  2. TX exists, exactly one CSV booking AND one DB booking
                           -> diff + UPDATE that booking (and the TX row).
  3. TX exists, bookings match 1:1 on `Unique Item Number`
                           -> diff + UPDATE each matched booking (and the TX row).
  4. TX exists, different booking counts / differing Unique Item Numbers
                           -> ERROR (abort before any write).

Idempotent: re-importing the same file changes nothing (verified).
Safety: writes go through ctx.require_approval_to_run_in_prod(); honors ctx.dry_run.
"""

from __future__ import annotations

import csv as _csv
import datetime as _dt
import decimal as _decimal
import logging as _logging
import pathlib as _pathlib
import sys as _sys
import uuid as _uuid

import wsjrdp2027
from psycopg.types.json import Jsonb


_SELF_NAME = _pathlib.Path(__file__).stem
_LOGGER = _logging.getLogger(__name__)

TX_TABLE = "moss_card_transactions"
BOOKING_TABLE = "moss_card_transaction_bookings"
CSV_DELIMITER = ";"
KEY_CSV = "Transaction ID"  # -> card_transaction_uuid
_UUID = "card_transaction_uuid"
_UIN = "unique_item_number"

# --- CSV header -> DB column, transaction level (identical across splits) ------
TX_COLUMN_MAP: dict[str, str] = {
    "Transaction ID": "card_transaction_uuid",
    "Transaction State": "transaction_state",
    "Transaction Type": "transaction_type",
    "General Transaction Type": "general_transaction_type",
    "Is Prepayment?": "is_prepayment",
    # dates
    "Payment Date": "payment_date",
    "Booking Date": "booking_date",
    "Settlement Date": "settlement_date",
    "First Export Date": "first_export_date",
    "Last Export Date": "last_export_date",
    "Receipt Date": "receipt_date",
    "Service Date": "service_date",
    "Approval Date": "approval_date",
    # NOTE: the transaction totals / currencies / rates have no dedicated column
    # any more.  `signed_total_base_amount` is computed from the booking lines
    # (and verified against "Total Amount"); every source field is mirrored
    # verbatim via ALWAYS_MIRROR_TX below.
    # merchant & supplier
    "Merchant Name": "merchant_name",
    "Merchant City": "merchant_city",
    "Merchant Country": "merchant_country",
    "Supplier Name": "supplier_name",
    "Supplier Account": "supplier_account_number",
    # accounting (transaction level)
    "Moss Balance Account": "moss_balance_account_number",
    "Cash in Transit Account": "cash_in_transit_account_number",
    # card & employee
    "Cardholder": "cardholder",
    "Card Used": "card_used",
    "Card Holder Name": "card_holder_name",
    "Card Holder Label": "card_holder_label",
    "Card Label": "card_label",
    "Card Purpose": "card_purpose",
    "Team Name": "team_name",
    "Approver Name": "approver_name",
    "Post Spend Approval Status": "post_spend_approval_status",
    # text / links / references
    "Reason for Purchase": "reason_for_purchase",
    "Parent Booking Text": "parent_booking_text",
    "Invoice Number": "invoice_number",
    "Invoice File Name": "invoice_file_name",
    "Sage Payment Type": "sage_payment_type",
    "Sage Transaction Type": "sage_transaction_type",
}

# --- CSV header -> DB column, booking level (differ per split) -----------------
BOOKING_COLUMN_MAP: dict[str, str] = {
    "Unique Item Number": "unique_item_number",
    "Sub-row Number": "sub_row_number",
    # Money house layer (doc/money_conventions.md): Moss Home = our base axis,
    # Moss Original = our transaction axis.  Moss delivers SIGNED amounts
    # (purchases negative), which is exactly our account-perspective convention
    # (R2), so they go in as-is; base_amount / transaction_amount / debit_credit
    # are generated columns.  The other line amounts have no dedicated column
    # any more and are mirrored verbatim (ALWAYS_MIRROR_BOOKING).
    "Home Amount": "signed_base_amount",
    "Original Amount": "signed_transaction_amount",
    "Home Currency": "base_currency",
    "Original Currency": "transaction_currency",
    "Account Number": "account_number",
    "Name of Expense Account": "name_of_expense_account",
    "Cost Center - Number": "cost_center_number",
    "Cost Carrier - Number": "sphere_number",
    "Distribution combination": "distribution_combination",
    "Note": "posting_text",
}

# Derived by the importer, not mapped 1:1 from a CSV column.
_BOOKING_DERIVED = ("account_kind", "exchange_rate")
# The Kontenart of the three chain accounts (R5); the matching *_type columns are
# generated by the DB from these.
_TX_ACCOUNT_KINDS = {
    "supplier_account_number": "supplier_account_kind",
    "moss_balance_account_number": "moss_balance_account_kind",
    "cash_in_transit_account_number": "cash_in_transit_account_kind",
}
_TX_DERIVED = ("signed_total_base_amount", *_TX_ACCOUNT_KINDS.values())

# >70%-empty CSV headers -> other_moss_columns[<key>] (only if a value is present).
OTHER_COLUMNS_TX: dict[str, str] = {
    "Record Type": "record_type",
    "Supplier IBAN": "supplier_iban",
    "Supplier BIC": "supplier_bic",
    "Supplier Vat ID": "supplier_vat_id",
    "VAT Code": "vat_code",
    "VAT Name": "vat_name",
    "VAT Rate": "vat_rate",
    "Card Acceptor Name": "card_acceptor_name",
    "Client Number": "client_number",
    "Airline Ticket Number": "airline_ticket_number",
    "Number of Months in Release Plan": "number_of_months_in_release_plan",
    "Prepayment Start Date": "prepayment_start_date",
    "Prepayment End Date": "prepayment_end_date",
}
OTHER_COLUMNS_BOOKING: dict[str, str] = {
    "Unit Price": "unit_price",
    "Quantity": "quantity",
    # No column of its own: undocumented by Moss and equal to "Account Number"
    # in every sample row -- kept verbatim in case it ever deviates.
    "Original Expense Account": "original_expense_account",
}

# Money/currency/rate columns that are ALWAYS mirrored into other_moss_columns
# under their verbatim Moss field-reference name -- even when a house column
# carries the same value (see the migration header).  Source fidelity beats
# storage: the house columns are derived and may change, the mirror always shows
# what Moss delivered.  Unlike OTHER_COLUMNS_*, an empty CSV cell is stored as ""
# (that the field was empty is itself the information).
ALWAYS_MIRROR_TX: tuple[str, ...] = (
    "Total Amount",
    "Total Amount (excl. VAT)",
    "Total Original Amount",
    "Total Original Amount (excl. VAT)",
    "VAT Amount",
    "Original VAT",
    "Fees Amount",
    "Currency",
    "Home Currency",
    "Original Currency",
    "Conversion Rate",
    "Conversion Rate Including Fees",
)
ALWAYS_MIRROR_BOOKING: tuple[str, ...] = (
    "Amount",
    "Amount (excl. VAT)",
    "Home Amount",
    "Original Amount",
    "Original Amount (excl. VAT)",
    "Transaction Amount Excluding Fees",
)
_CSV_TOTAL_AMOUNT = "Total Amount"  # cross-checked against the sum of the lines

# CSV header -> transaction other_moss_columns key; stored ONLY if the CSV value
# differs from the value derived from the Transaction ID.
DERIVED_FROM_UUID: dict[str, str] = {
    "Moss Record URL": "moss_record_url",
    "Moss Attachment URL": "moss_attachment_url",
    "Transaction ID PDF filename": "transaction_id_pdf_filename",
}

# Present in the CSV but never stored (derivable/redundant; see doc 5.2.7).
IGNORED = {
    "Cost Center - Name",
    "Cost Carrier - Name",
    "Card Name",
    "Category",  # entfernt (siehe doc 5.2.7)
    "Period",
    "Period Day",
    "Period Month (double-digit)",
    "Accounting Period",
}
# Being removed from the WSJ27 export; tolerated (and ignored) if still present.
NOT_EXPORTED = {
    "CSV Line Type",
    "Month end date",
    "Row Number",
    "Transaction Ordinal",
    "Sub Item Row Number",
    "Merchant and Card Description",
}

_MOSS_RECORD_URL_PREFIX = "https://getmoss.com/app/transactions/all/"

# Type coercion for DB columns.
_DATE_COLS = {
    "payment_date",
    "booking_date",
    "settlement_date",
    "first_export_date",
    "last_export_date",
    "receipt_date",
    "service_date",
    "approval_date",
}
_DECIMAL_COLS = {
    "signed_base_amount",
    "signed_transaction_amount",
    "signed_total_base_amount",
    "exchange_rate",
}
_INT_COLS = {"sub_row_number"}
# NOT NULL string columns: keep "" rather than NULL when the CSV cell is empty.
_NOT_NULL_STR_COLS = {"posting_text"}

_TX_WRITE = [*TX_COLUMN_MAP.values(), *_TX_DERIVED, "source_file", "other_moss_columns"]
_BOOKING_WRITE = [
    _UUID,
    *BOOKING_COLUMN_MAP.values(),
    *_BOOKING_DERIVED,
    "source_file",
    "other_moss_columns",
]
# Columns compared on re-import (other_moss_columns is diffed separately, and
# the generated columns are not written at all).
_TX_DIFF = [*TX_COLUMN_MAP.values(), *_TX_DERIVED]
_BOOKING_DIFF = [*BOOKING_COLUMN_MAP.values(), *_BOOKING_DERIVED]


def _derived_url_values(transaction_id: str) -> dict[str, str]:
    record = f"{_MOSS_RECORD_URL_PREFIX}{transaction_id}"
    return {
        "moss_record_url": record,
        "moss_attachment_url": record.removeprefix("https://"),
        "transaction_id_pdf_filename": f"{transaction_id}.pdf",
    }


def _coerce(db_col: str, raw: str):
    value = (raw or "").strip()
    if value == "":
        return "" if db_col in _NOT_NULL_STR_COLS else None
    if db_col in _DATE_COLS:
        return _dt.date.fromisoformat(value)
    if db_col in _DECIMAL_COLS:
        return _decimal.Decimal(value.replace(",", "."))
    if db_col in _INT_COLS:
        return int(value)
    return value


def _mapped(csv_row: dict[str, str], column_map: dict[str, str]) -> dict[str, object]:
    return {
        db: _coerce(db, csv_row.get(header, "")) for header, db in column_map.items()
    }


def _account_kind(number: object) -> str:
    """Kontenart of an account number taken from a _mapped() record. Those
    records are typed `object` (they mix str/None/date/Decimal/int, see
    _coerce); the account-number columns are never coerced, so they are always
    str or None."""
    return wsjrdp2027.datev.account_kind_for_account_number(
        number if isinstance(number, str) else None
    )


def _other(csv_row: dict[str, str], other_map: dict[str, str]) -> dict[str, object]:
    result: dict[str, object] = {}
    for header, key in other_map.items():
        val = (csv_row.get(header) or "").strip()
        if val:
            result[key] = val
    return result


def _mirror(csv_row: dict[str, str], headers: tuple[str, ...]) -> dict[str, object]:
    """Verbatim mirror of the money/currency columns (see ALWAYS_MIRROR_*).

    Keyed by the Moss field-reference name, value the raw CSV string; empty
    cells are kept as "".  Columns missing from the file are skipped."""
    return {h: (csv_row.get(h) or "").strip() for h in headers if h in csv_row}


def _exchange_rate(base, transaction, base_currency, transaction_currency):
    """transaction = base * exchange_rate, derived as |transaction| / |base|.

    Quantity notation (Mengennotierung): transaction-currency units per one unit
    of the base currency, e.g. EUR->PLN ~ 4.24. Same direction DATEV delivers in
    its Kurs field, so the rates of both tables are comparable (see
    doc/fin/money_conventions.md R4).

    Equal amounts mean a rate of exactly 1 -- that is the normal case here (both
    figures in EUR), and storing 1 instead of NULL keeps `base * exchange_rate`
    usable without a NULL check. NULL is left for the cases where no rate can be
    derived: a missing amount, a zero base, or the contradictory combination of
    one currency with two different amounts.

    Moss's own Conversion Rate is unreliable (observed constant 1.0/NULL even on
    genuine FX rows), so it is never used here; it is kept verbatim in
    other_moss_columns."""
    if base is None or transaction is None:
        return None
    if base == transaction:
        return _decimal.Decimal(1)
    if base_currency == transaction_currency or not base:
        return None
    return abs(transaction) / abs(base)


def _row_to_records(csv_row: dict[str, str]) -> tuple[dict, dict]:
    """One CSV row -> (transaction record, booking record)."""
    tx = _mapped(csv_row, TX_COLUMN_MAP)
    tx_other = _other(csv_row, OTHER_COLUMNS_TX) | _mirror(csv_row, ALWAYS_MIRROR_TX)
    transaction_id = (csv_row.get(KEY_CSV) or "").strip()
    derived = _derived_url_values(transaction_id)
    for header, key in DERIVED_FROM_UUID.items():
        val = (csv_row.get(header) or "").strip()
        if val and val != derived[key]:
            tx_other[key] = val
    for number_col, kind_col in _TX_ACCOUNT_KINDS.items():
        tx[kind_col] = _account_kind(tx[number_col])
    tx["other_moss_columns"] = tx_other

    # The card_transaction_uuid columns are of type uuid: keep the key typed
    # (a str would neither match the fetched rows nor bind against uuid[]).
    # The URL derivation above deliberately uses the verbatim CSV spelling.
    try:
        transaction_uuid = _uuid.UUID(transaction_id)
    except ValueError:
        raise ValueError(
            f"CSV row with malformed Transaction ID {transaction_id!r} "
            "(expected a UUID)"
        ) from None
    tx[_UUID] = transaction_uuid

    booking = _mapped(csv_row, BOOKING_COLUMN_MAP)
    booking[_UUID] = transaction_uuid  # natural-key FK to the transaction
    booking["other_moss_columns"] = _other(csv_row, OTHER_COLUMNS_BOOKING) | _mirror(
        csv_row, ALWAYS_MIRROR_BOOKING
    )
    # Accounting is kept in EUR; refuse anything else rather than silently
    # storing a non-EUR "base" amount (the DB check constraint would fail too).
    if booking["base_currency"] != "EUR":
        raise SystemExit(
            f"Transaction {transaction_id}: Home Currency is "
            f"{booking['base_currency']!r}, expected EUR -- refusing the import."
        )
    booking["account_kind"] = _account_kind(booking["account_number"])
    booking["exchange_rate"] = _exchange_rate(
        booking["signed_base_amount"],
        booking["signed_transaction_amount"],
        booking["base_currency"],
        booking["transaction_currency"],
    )
    return tx, booking


def _validate_headers(headers: list[str], csv_filename: str) -> None:
    known = (
        set(TX_COLUMN_MAP)
        | set(BOOKING_COLUMN_MAP)
        | set(OTHER_COLUMNS_TX)
        | set(OTHER_COLUMNS_BOOKING)
        | set(DERIVED_FROM_UUID)
        | set(ALWAYS_MIRROR_TX)
        | set(ALWAYS_MIRROR_BOOKING)
        | IGNORED
        | NOT_EXPORTED
    )
    unknown = [h for h in headers if h not in known]
    if unknown:
        raise SystemExit(
            f"{csv_filename}: unbekannte CSV-Spalten (bitte klassifizieren): {unknown}"
        )


def _read_grouped(csv_filenames: list[str]):
    """Return {uuid: (tx_record, [booking_record, ...])}, grouped over all files."""
    tx_by_uuid: dict[str, dict] = {}
    bookings_by_uuid: dict[str, list[dict]] = {}
    for csv_filename in csv_filenames:
        _LOGGER.info("Moss card-transaction CSV: %s", csv_filename)
        with open(csv_filename, newline="", encoding="utf-8-sig") as fh:
            reader = _csv.DictReader(fh, delimiter=CSV_DELIMITER)
            _validate_headers(list(reader.fieldnames or []), csv_filename)
            source_file = _pathlib.Path(csv_filename).name
            for csv_row in reader:
                tx, booking = _row_to_records(csv_row)
                tx["source_file"] = booking["source_file"] = source_file
                uuid = tx[_UUID]
                if uuid in tx_by_uuid and _changed(
                    tx, tx_by_uuid[uuid], TX_COLUMN_MAP.values()
                ):
                    _LOGGER.warning(
                        "Transaction ID %s: uneinheitliche Transaktions-Felder über Splits",
                        uuid,
                    )
                tx_by_uuid.setdefault(uuid, tx)
                bookings_by_uuid.setdefault(uuid, []).append(booking)

    grouped = {}
    for uuid, tx in tx_by_uuid.items():
        bookings = bookings_by_uuid[uuid]
        tx["signed_total_base_amount"] = sum(b["signed_base_amount"] for b in bookings)
        _verify_total(uuid, tx, bookings)
        grouped[uuid] = (tx, bookings)
    return grouped


def _verify_total(uuid, tx: dict, bookings: list[dict]) -> None:
    """Cross-check the computed total against the Moss "Total Amount" mirror.

    Only comparable when the transaction is booked in our base currency (the
    Moss total is in the booking currency, our total in the base currency)."""
    mirror = tx["other_moss_columns"]
    if mirror.get("Currency") != mirror.get("Home Currency"):
        return
    raw = (mirror.get(_CSV_TOTAL_AMOUNT) or "").strip()
    if not raw:
        return
    moss_total = _decimal.Decimal(raw.replace(",", "."))
    computed = tx["signed_total_base_amount"]
    if moss_total != computed:
        raise SystemExit(
            f"Transaction {uuid}: Moss {_CSV_TOTAL_AMOUNT} ({moss_total}) does not "
            f"match the sum of its {len(bookings)} booking line(s) ({computed})."
        )


# --- diffing ------------------------------------------------------------------


def _as_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, _decimal.Decimal):
        return format(value.normalize(), "f")
    if isinstance(value, _dt.date):
        return value.isoformat()
    return str(value)


def _changed(new_rec: dict, db_row: dict, columns) -> dict:
    """Mapped columns (+ other_moss_columns) whose new value differs from the stored one."""
    changed = {}
    for col in columns:
        if _as_text(new_rec.get(col)) != _as_text(db_row.get(col)):
            changed[col] = new_rec.get(col)
    if (new_rec.get("other_moss_columns") or {}) != (
        db_row.get("other_moss_columns") or {}
    ):
        changed["other_moss_columns"] = new_rec.get("other_moss_columns") or {}
    return changed


# --- DB access ----------------------------------------------------------------


def _fetch_rows(cur, table: str, columns: list[str], where: str, param) -> list[dict]:
    cur.execute(f"SELECT {', '.join(columns)} FROM {table} WHERE {where}", (param,))
    names = [d.name for d in cur.description]
    return [dict(zip(names, values)) for values in cur.fetchall()]


def _fetch_tx(cur, uuids: list[str]) -> dict[str, dict]:
    if not uuids:
        return {}
    columns = [*TX_COLUMN_MAP.values(), *_TX_DERIVED, "id", "other_moss_columns"]
    rows = _fetch_rows(cur, TX_TABLE, columns, f"{_UUID} = ANY(%s)", uuids)
    return {r[_UUID]: r for r in rows}


def _fetch_bookings(cur, uuids: list[str]) -> dict[str, list[dict]]:
    if not uuids:
        return {}
    columns = [
        *BOOKING_COLUMN_MAP.values(),
        *_BOOKING_DERIVED,
        "id",
        _UUID,
        "other_moss_columns",
    ]
    rows = _fetch_rows(cur, BOOKING_TABLE, columns, f"{_UUID} = ANY(%s)", uuids)
    by_uuid: dict[str, list[dict]] = {}
    for r in rows:
        by_uuid.setdefault(r[_UUID], []).append(r)
    return by_uuid


def _insert_tx(cur, tx_rec: dict) -> None:
    placeholders = ", ".join(["%s"] * len(_TX_WRITE))
    params = [
        Jsonb(tx_rec[c]) if c == "other_moss_columns" else tx_rec[c] for c in _TX_WRITE
    ]
    cur.execute(
        f"INSERT INTO {TX_TABLE} ({', '.join(_TX_WRITE)}) VALUES ({placeholders})",
        params,
    )


def _insert_bookings(cur, bookings: list[dict]) -> None:
    placeholders = ", ".join(["%s"] * len(_BOOKING_WRITE))
    sql = f"INSERT INTO {BOOKING_TABLE} ({', '.join(_BOOKING_WRITE)}) VALUES ({placeholders})"
    params = [
        [Jsonb(b[c]) if c == "other_moss_columns" else b[c] for c in _BOOKING_WRITE]
        for b in bookings
    ]
    cur.executemany(sql, params)


def _update_row(cur, table: str, db_id: int, changed: dict) -> None:
    set_sql = ", ".join(f"{c} = %s" for c in changed)
    params = [Jsonb(v) if c == "other_moss_columns" else v for c, v in changed.items()]
    cur.execute(
        f"UPDATE {table} SET {set_sql}, updated_at = NOW() WHERE id = %s",
        [*params, db_id],
    )


# --- import -------------------------------------------------------------------


def _import(cur, grouped: dict, *, dry_run: bool) -> None:
    existing_tx = _fetch_tx(cur, list(grouped))
    existing_bookings = _fetch_bookings(cur, list(existing_tx))

    errors: list[str] = []
    n_tx_ins = n_tx_upd = n_bk_ins = n_bk_upd = 0

    for uuid, (tx_rec, booking_recs) in grouped.items():
        if uuid not in existing_tx:  # case 1: new transaction
            n_tx_ins += 1
            n_bk_ins += len(booking_recs)
            if not dry_run:
                _insert_tx(cur, tx_rec)
                _insert_bookings(cur, booking_recs)
            continue

        db_tx = existing_tx[uuid]
        tx_changed = _changed(tx_rec, db_tx, _TX_DIFF)
        if tx_changed:
            tx_changed["source_file"] = tx_rec["source_file"]
            n_tx_upd += 1
            if not dry_run:
                _update_row(cur, TX_TABLE, db_tx["id"], tx_changed)

        matched = _match_bookings(
            uuid, booking_recs, existing_bookings.get(uuid, []), errors
        )
        if matched is None:
            continue
        for booking_rec, db_booking in matched:
            bk_changed = _changed(booking_rec, db_booking, _BOOKING_DIFF)
            if bk_changed:
                bk_changed["source_file"] = booking_rec["source_file"]
                n_bk_upd += 1
                if not dry_run:
                    _update_row(cur, BOOKING_TABLE, db_booking["id"], bk_changed)

    if errors:
        for msg in errors:
            _LOGGER.error("%s", msg)
        raise SystemExit(
            f"Abbruch: {len(errors)} Transaktion(en) ohne klares Buchungs-Match."
        )

    _LOGGER.info(
        "Transaktionen: %d | TX INSERT/UPDATE: %d/%d | Buchungen INSERT/UPDATE: %d/%d",
        len(grouped),
        n_tx_ins,
        n_tx_upd,
        n_bk_ins,
        n_bk_upd,
    )


def _match_bookings(uuid, booking_recs, db_bookings, errors):
    """Return [(csv_booking, db_booking), ...] or None (recording a case-4 error)."""
    if len(booking_recs) == 1 and len(db_bookings) == 1:  # case 2
        return [(booking_recs[0], db_bookings[0])]
    csv_by_uin = {b[_UIN]: b for b in booking_recs}
    db_by_uin = {b[_UIN]: b for b in db_bookings}
    clean = (
        len(csv_by_uin) == len(booking_recs)
        and len(db_by_uin) == len(db_bookings)
        and set(csv_by_uin) == set(db_by_uin)
    )
    if not clean:  # case 4
        errors.append(
            f"Transaction ID {uuid}: Buchungen CSV={len(booking_recs)} DB={len(db_bookings)}; "
            f"Unique Item Numbers CSV={sorted(csv_by_uin)} DB={sorted(db_by_uin)}"
        )
        return None
    return [(csv_by_uin[uin], db_by_uin[uin]) for uin in csv_by_uin]  # case 3


def create_argument_parser():
    import argparse

    p = argparse.ArgumentParser(description="Import Moss WSJ27 card transactions")
    p.add_argument("csv_files", nargs="+", help="Moss WSJ27 card-transaction CSV(s)")
    return p


def main(argv=None):
    ctx = wsjrdp2027.WsjRdpContext(argument_parser=create_argument_parser(), argv=argv)
    out_base = ctx.make_out_path(_SELF_NAME)
    ctx.configure_log_file(out_base.with_suffix(".log"))

    grouped = _read_grouped(ctx.parsed_args.csv_files)

    with ctx.psycopg_connect() as conn:
        if not ctx.dry_run:
            ctx.require_approval_to_run_in_prod()
        with conn.cursor() as cur:
            _import(cur, grouped, dry_run=ctx.dry_run)
        if ctx.dry_run:
            _LOGGER.info("[dry-run] Keine Änderungen geschrieben.")
            conn.rollback()
        else:
            conn.commit()

    _LOGGER.info("Output directory: %s", ctx.out_dir)


if __name__ == "__main__":
    _sys.exit(main())
